# SPDX-License-Identifier: MIT OR Apache-2.0
"""`ftcheck matrix` — free-threaded wheel jobs for a release workflow.

**A stopgap.** Many projects hand-roll these jobs. maturin's `main` branch
(September 2026) discovers free-threaded 3.14+ interpreters and can generate
free-threaded jobs; this command is for projects whose maturin version or
generated workflow does not cover the interpreters and platforms they need.
The logic is kept small, and maturin is where it belongs.

What it emits:

- Linux (manylinux and musllinux, x86-64 and aarch64) through
  `PyO3/maturin-action`, naming each free-threaded interpreter explicitly,
  so the build does not depend on interpreter discovery.
- macOS and Windows jobs that install each interpreter with
  `actions/setup-python` (which has supported `t` versions since PR #973) and
  hand maturin its exact path.
- Optionally an `abi3t` job for PEP 803 (Python 3.15+), emitted **disabled**:
  abi3t support in maturin and PyO3 is new, and the job should be enabled
  only once the project's versions are confirmed to build an abi3t wheel.
"""
from __future__ import annotations

import pathlib
import tomllib
from dataclasses import dataclass, field

__all__ = ["PLATFORMS", "Matrix", "load_project", "render"]

# name -> (runner, maturin target, manylinux value or None for native runners)
PLATFORMS = {
    "manylinux-x86_64": ("ubuntu-latest", "x86_64", "auto"),
    "manylinux-aarch64": ("ubuntu-24.04-arm", "aarch64", "auto"),
    "musllinux-x86_64": ("ubuntu-latest", "x86_64-unknown-linux-musl", "musllinux_1_2"),
    "musllinux-aarch64": ("ubuntu-24.04-arm", "aarch64-unknown-linux-musl", "musllinux_1_2"),
    "macos-arm64": ("macos-14", "aarch64", None),
    "macos-x86_64": ("macos-13", "x86_64", None),
    "windows-x86_64": ("windows-latest", "x64", None),
}
DEFAULT_PLATFORMS = ["manylinux-x86_64", "manylinux-aarch64", "musllinux-x86_64", "macos-arm64",
                     "windows-x86_64"]
# What public PyO3 projects that hand-roll these jobs ship today (checked
# 2026-09-24). 3.13t can be requested; it was
# experimental and carries CPython races fixed only in 3.14.
DEFAULT_PYTHONS = ["3.14t", "3.15t"]


@dataclass
class Matrix:
    pythons: list[str] = field(default_factory=lambda: list(DEFAULT_PYTHONS))
    platforms: list[str] = field(default_factory=lambda: list(DEFAULT_PLATFORMS))
    abi3t: bool = False
    manifest_path: str | None = None
    notes: list[str] = field(default_factory=list)


def load_project(path: pathlib.Path) -> tuple[str | None, list[str]]:
    """(maturin manifest-path, notes about the project worth stating)."""
    notes: list[str] = []
    manifest = None
    pyproject = path / "pyproject.toml"
    if pyproject.is_file():
        data = tomllib.loads(pyproject.read_text())
        manifest = data.get("tool", {}).get("maturin", {}).get("manifest-path")
    cargo = path / (manifest or "Cargo.toml")
    if cargo.is_file():
        text = cargo.read_text()
        if "abi3" in text:
            notes.append(
                "The crate enables PyO3's abi3 feature. abi3 wheels are incompatible with the "
                "free-threaded ABI, so PyO3 builds version-specific wheels for the t "
                "interpreters below; your abi3 jobs are unaffected."
            )
    else:
        notes.append(f"No Cargo manifest found at {cargo}; emitting jobs for the project root.")
    return manifest, notes


def _validate(m: Matrix) -> None:
    unknown = [p for p in m.platforms if p not in PLATFORMS]
    if unknown:
        raise ValueError(f"unknown platform(s) {unknown}; choose from {sorted(PLATFORMS)}")
    bad = [p for p in m.pythons if not p.endswith("t") or not p[:-1].replace(".", "").isdigit()]
    if bad:
        raise ValueError(f"not free-threaded interpreter versions: {bad} (expected e.g. 3.14t)")


def _args(m: Matrix, interpreters: str) -> str:
    args = f"--release --out dist -i {interpreters}"
    if m.manifest_path:
        args += f" --manifest-path {m.manifest_path}"
    return args


def render(m: Matrix) -> str:
    """GitHub Actions YAML: a complete workflow (triggered by version tags and
    manually); its `jobs:` can also be merged into an existing release workflow."""
    _validate(m)
    linux = [p for p in m.platforms if PLATFORMS[p][2] is not None]
    native = [p for p in m.platforms if PLATFORMS[p][2] is None]
    interpreters = " ".join(f"python{v}" for v in m.pythons)
    out: list[str] = [
        "# Free-threaded wheel jobs, generated by `ftcheck matrix`.",
        "#",
        "# A STOPGAP: check what `maturin generate-ci github` emits for this",
        "# project first. Remove these jobs once maturin's generated workflow",
        "# covers the free-threaded interpreters and platforms you need.",
    ]
    for note in m.notes:
        out.append("#")
        out.extend(f"# NOTE: {line}" for line in _wrap_comment(note))
    # A complete workflow, so redirecting the output into
    # .github/workflows/ gives a file GitHub accepts (a bare `jobs:` block
    # does not load — found by a first user following the docs).
    out += [
        "name: free-threaded wheels",
        "on:",
        "  push:",
        "    tags: ['v*']",
        "  workflow_dispatch:",
    ]
    out.append("jobs:")

    if linux:
        out += [
            "  free-threaded-linux:",
            "    name: free-threaded wheels (${{ matrix.platform.name }})",
            "    runs-on: ${{ matrix.platform.runner }}",
            "    strategy:",
            "      fail-fast: false",
            "      matrix:",
            "        platform:",
        ]
        for name in linux:
            runner, target, manylinux = PLATFORMS[name]
            out += [
                f"          - name: {name}",
                f"            runner: {runner}",
                f"            target: {target}",
                f"            manylinux: {manylinux}",
            ]
        out += [
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: PyO3/maturin-action@v1",
            "        with:",
            "          target: ${{ matrix.platform.target }}",
            "          manylinux: ${{ matrix.platform.manylinux }}",
            "          # Named explicitly: the images ship these interpreters,",
            "          # but maturin's interpreter discovery skips them.",
            f"          args: {_args(m, interpreters)}",
            "      - uses: actions/upload-artifact@v4",
            "        with:",
            "          name: wheels-free-threaded-${{ matrix.platform.name }}",
            "          path: dist",
        ]

    if native:
        out += [
            "  free-threaded-native:",
            "    name: free-threaded wheels (${{ matrix.platform.name }}, ${{ matrix.python }})",
            "    runs-on: ${{ matrix.platform.runner }}",
            "    strategy:",
            "      fail-fast: false",
            "      matrix:",
            f"        python: [{', '.join(repr(v) for v in m.pythons)}]",
            "        platform:",
        ]
        for name in native:
            runner, target, _ = PLATFORMS[name]
            out += [
                f"          - name: {name}",
                f"            runner: {runner}",
                f"            target: {target}",
            ]
        out += [
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: actions/setup-python@v5",
            "        id: python",
            "        with:",
            "          python-version: ${{ matrix.python }}",
            "      - uses: PyO3/maturin-action@v1",
            "        with:",
            "          target: ${{ matrix.platform.target }}",
            f"          args: {_args(m, '${{ steps.python.outputs.python-path }}')}",
            "      - uses: actions/upload-artifact@v4",
            "        with:",
            "          name: wheels-free-threaded-${{ matrix.platform.name }}-${{ matrix.python }}",
            "          path: dist",
        ]

    if m.abi3t:
        out += [
            "  # PEP 803: one stable free-threaded ABI (abi3t) from Python 3.15.",
            "  # DISABLED until you have confirmed that your maturin and PyO3",
            "  # versions build an abi3t wheel for this project. Once enabled and",
            "  # working, the per-version free-threaded jobs above can be retired.",
            "  free-threaded-abi3t:",
            "    if: false",
            "    name: abi3t wheel (Python >= 3.15)",
            "    runs-on: ubuntu-latest",
            "    steps:",
            "      - uses: actions/checkout@v4",
            "      - uses: PyO3/maturin-action@v1",
            "        with:",
            "          manylinux: auto",
            f"          args: {_args(m, 'python3.15t')}",
            "      - uses: actions/upload-artifact@v4",
            "        with:",
            "          name: wheels-abi3t",
            "          path: dist",
        ]
    return "\n".join(out) + "\n"


def _wrap_comment(text: str, width: int = 72) -> list[str]:
    words, lines, line = text.split(), [], ""
    for w in words:
        if len(line) + len(w) + 1 > width:
            lines.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        lines.append(line)
    return lines
